version: 1.0.{build}
image: Visual Studio 2015
build_script:
- cmd: >-
    git submodule update --init --recursive

    choco install -y swig --version 3.0.12

    setenv.bat

    msbuild.exe x64dbgpy.sln /verbosity:minimal /t:Build /p:Configuration=Release;Platform=Win32

    msbuild.exe x64dbgpy.sln /verbosity:minimal /t:Build /p:Configuration=Release;Platform=x64

    call install32.bat

    call install64.bat
artifacts:
- path: release
